model = "gpt-5.3-codex"
model_reasoning_effort = "high"
model_reasoning_summary = "auto"

approval_policy = "on-request"
sandbox_mode = "workspace-write"

[sandbox_workspace_write]
network_access = true

[features]
rmcp_client = true

[model_providers.azure]
name = "Azure"
base_url = "https://<YOUR_RESOURCE_NAME>.openai.azure.com/openai"
env_key = "AZURE_OPENAI_API_KEY"
query_params = { api-version = "2025-04-01-preview" }
wire_api = "responses"

[profiles.azure]
model = "gpt-5.2-codex"
model_provider = "azure"

[mcp_servers.github-mcp-server]
url = "https://api.githubcopilot.com/mcp/"
bearer_token_env_var = "GITHUB_MCP_API_TOKEN"

[mcp_servers.playwright]
command = "npx"
args = ["-y", "@playwright/mcp"]

[mcp_servers.markitdown]
command = "uvx"
args = ["markitdown-mcp"]

[mcp_servers.serena]
command = "uvx"
args = [
  "--from",
  "git+https://github.com/oraios/serena",
  "serena",
  "start-mcp-server",
  "--context",
  "codex",
  "--enable-web-dashboard=false",
  "--project",
  "$(pwd)",
]
startup_timeout_sec = 30

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp", "--api-key", "<CONTEXT7_API_KEY>"]
[mcp_servers.azure-devops]
command = "npx"
args = [
  "-y",
  "@azure-devops/mcp",
  "--authentication",
  "envvar",
  "<YOUR_ORG_NAME>",
]
[mcp_servers.azure-devops.env]
ADO_MCP_AUTH_TOKEN = "<YOUR_PERSONAL_ACCESS_TOKEN>"
